# @package _global_
defaults:
  - inference_base
  - _self_

run_name_: eval_60m_baseline_v2

ckpt_path: /rds/user/sr2173/hpc-work/proteina/store/proteina_60m_baseline_v2/checkpoints
ckpt_name: last-EMA.ckpt

self_cond: True

# Sampling params
sampling_caflow:
  sampling_mode: sc
  sc_scale_noise: 0.45

# Protein lengths and sample count (full eval, extended to max training length)
nres_lens:
min_len: 60
max_len: 500
step_len: 10
nsamples_per_len: 125
generation_batch_size: 8

# Eval mode
compute_designability: False
compute_fid: True
metric_factory:
  - metrics: ["FID", "fJSD_C", "fJSD_A", "fJSD_T"]
    ckpt_path: ${oc.env:DATA_PATH}/metric_factory/model_weights/gearnet_ca.pth
    real_features_path: ${oc.env:DATA_PATH}/metric_factory/features/pdb_eval_ca_features.pth
    ca_only: True
    prefix: PDB_
  - metrics: ["FID", "fJSD_C", "fJSD_A", "fJSD_T"]
    ckpt_path: ${oc.env:DATA_PATH}/metric_factory/model_weights/gearnet_ca.pth
    real_features_path: ${oc.env:DATA_PATH}/metric_factory/features/D_FS_eval_ca_features.pth
    ca_only: True
    prefix: AFDB_
  - metrics: ["fS_C", "fS_A", "fS_T"]
    ckpt_path: ${oc.env:DATA_PATH}/metric_factory/model_weights/gearnet_ca.pth
    ca_only: True
