# @package _global_
defaults:
  - inference_fid_60m_baseline_128_lite
  - _self_

run_name_: eval_60m_repa_l4_128_bs80_lr3x_lite

ckpt_path: /rds/user/sr2173/hpc-work/proteina/store/proteina_60m_repa_l4_128_per_residue_bs80_lr3x/checkpoints
