# @package _global_
defaults:
  - inference_fid_60m_baseline_512_sm_lite
  - _self_

run_name_: eval_60m_repa_l0_512_sm_lite

ckpt_path: /rds/user/sr2173/hpc-work/proteina/store/proteina_60m_repa_layer0_v2/checkpoints
# overridden at sweep-time to step 750K (3.0M samples @ bs=4)
