# @package _global_
defaults:
  - /training_ca
  - _self_

run_name_: proteina_60m_repa_l1_128_afdb_per_sample

dataset: afdb_swissprot_lmdb_128
dataset_config_subdir: afdb

compile: true

opt:
  val_check_interval: 10000000

log:
  wandb_project: proteina-repa
  checkpoint_every_n_steps: 100000
  last_ckpt_every_n_steps: 3500

ema:
  validate_original_weights: True

repa:
  encoder:
    type: gearnet
    gearnet_ckpt_path: ${oc.env:DATA_PATH}/metric_factory/model_weights/gearnet_ca.pth
  layers: [1]
  lambda_repa: 0.5
  combination_mode: additive
  similarity_type: cosine
  averaging: per_sample
  projector_hidden_dim: 512
  projector_num_layers: 3

eval_callback:
  enabled: false
  compute_every_n_steps: 50000
  num_samples: 30
  length: 100
  compute_gearnet: true
  compute_designability: false
  compute_diversity: true
  gearnet_ckpt_path: ${oc.env:DATA_PATH}/metric_factory/model_weights/gearnet_ca.pth
